[package]
name = "mysql-connection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "17.0.0"
rocket = "0.5.0-rc.2"
rocket_contrib = "0.4.11"
rocket-json-response = "0.6.3"